### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by edsrzf**
The main one is the final commit, which streams JSON from messages.

@pyeremenko, would you please review and, once this is merged, release a new version?

### CODE REVIEW

**Comment by arschles** [comment]
@edsrzf LGTM

are there any multi-threaded tests? I admit I didn't look at or run any

**Comment by edsrzf** [comment]
No, I don't think there are

**Comment by arschles** [comment]
I'm getting tests running on my machine so I can write some. gonna push em to this branch

**Comment by alex-litvak** [comment]
@pyeremenko looks good for me. Can we merge it after running integration tests?

**Comment by carimura** [comment]
@arschles let's get the multi thread tests in today and merge this PR.

**Comment by pax95** [comment]
You should have a look at #84 before doing a release.

**Comment by carimura** [comment]
@pax95 that's this one?

**Comment by arschles** [comment]
@edsrzf @pyeremenko @alex-litvak I'm writing new tests but existing tests fail. I think because of a configuration problem on my machine. all tests fail with this exception trace:

```java
io.iron.ironmq.HTTPException: Invalid project/token combination
	at io.iron.ironmq.Client.singleRequest(Client.java:255)
	at io.iron.ironmq.Client.request(Client.java:183)
	at io.iron.ironmq.Client.patch(Client.java:172)
	at io.iron.ironmq.Queue.update(Queue.java:813)
	at io.iron.ironmq.IronMQTest.testReplaceSubscribers(IronMQTest.java:723)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

I have tried putting an `.iron.json` file in `config/` and also in my home directory. below is the file.

```json
{
  "token": "my_token",
  "project_id": "my_project_id",
}
```

this is my first time running tests on this codebase. do you know what the problem is?

**Comment by pax95** [comment]
@carimura mybad I ment #82

**Comment by arschles** [comment]
@carimura @treeder can I get push access to this repo so I can commit directly to this branch?

**Comment by treeder** [comment]
done.

**Comment by arschles** [comment]
thanks. @edsrzf when you're available, please let me know if you have any ideas on what's misconfigured or otherwise not working on my machine

**Comment by freeman1988** [comment]
@arschles just create `config.properties` file with next content:
```
token=
project_id=
```
in the root of the project

**Comment by freeman1988** [comment]
sorry, it is for v1

**Comment by arschles** [comment]
@edsrzf LGTM

@pyeremenko fixed tests in https://github.com/iron-io/iron_mq_java/pull/86. merged that into here and now we're good to go. @pyeremenko can you release this?

**Comment by pyeremenko** [comment]
I think we need to merge it before publishing

**Comment by arschles** [comment]
@pyeremenko merged & ready to publish

**Pull request merged**
