### PR TITLE
Set HTTP request timeout to 60 sec

### PR DESCRIPTION
**Pull request by alex-litvak**
@edsrzf Can you take a look please?

### CODE REVIEW

**Comment by smatei** [comment]
Hi, 

I am the one that insisted for this timeout. Our scripts were blocked by a stuck queue last week.

Please set a read timeout too. 

Best Regards,
Stefan Matei

**Comment by edsrzf** [comment]
Looks good so far. Please add a call to `setReadTimeout` as requested by @smatei.

**Comment by smatei** [comment]
Hi,

We are working with the php library too. When the queue went wild the php scripts were blocked too. I have looked over the code and there was a connect timeout set. Maybe you can get someone to check this too.

IronCore.php

public $connection_timeout = 60;
.....
curl_setopt($this->curl, CURLOPT_CONNECTTIMEOUT, $this->connection_timeout);

Best Regards,
Stefan Matei

**Comment by pax95** [comment]
Would have been nice if timeout where configurable instead of hardcoded values

**Comment by smatei** [comment]
@pax95 it is better than before (infinite timeout), but I agree with you. maybe I want to set a lower timeout value.

**Comment by edsrzf** [comment]
I'm going to merge this as is now. If someone wants to follow up and make it configurable, feel free.

**Comment by smatei** [comment]
Hi @alex-litvak @edsrzf 

I have a queue that times out right now. Read timeout

https://hud-e.iron.io/mq/mq-aws-us-east-1-1/projects/51da60a9ace3151424000044/queues/google_US_high

It was blocking the php scripts, because it had only connect timeout. I have added

curl_setopt($this->curl, CURLOPT_TIMEOUT, 20);

now it times out properly.

Can any of you fix my queue? Support is not responding in weekend.
iron io


Best regards,
Stefan Matei

**Comment by edsrzf** [comment]
@smatei I'm not seeing the error you are. I wasn't able to find a support conversation for this issue so I'm not sure if someone's already helped you out or if the problem resolved itself.

**Comment by smatei** [comment]
Hi @edsrzf,

I see that it is fixed now. What about the php timeout? Will you add a bug to the php library?

Best Regards,
Stefan Matei

**Comment by alex-litvak** [comment]
Hi @smatei,
This is not the best place to discuss php library. You can open a new issue [here](https://github.com/iron-io/iron_mq_php/issues) or continue in email thread (support@iron.io).

P.S. I see the connection timeout is set in [php](https://github.com/iron-io/iron_core_php/blob/master/src/IronCore.php#L286)

**Comment by smatei** [comment]
Hi @alex-litvak,

I will open a new issue for the php library. There was a connect timeout set, but it was a read timeout that kept the script going forever. I fixed it with this

curl_setopt($this->curl, CURLOPT_TIMEOUT, 20);

Best Regards,
Stefan Matei

**Pull request merged**
